### PR TITLE
Meteor integration

### PR DESCRIPTION
**Pull request by mordka**
Hi Antoine,

I'm a Meteor.js dev and volunteer package maintainer for Meteor. PruneCluster is a great efficient library, and adding it to Meteor's ecosystem will expose it to many new devs (Meteor has 20k+ stars on GitHub), likely bringing in new testers and contributors. It will also grab more attention from the users of the alternative library: [markercluster](https://github.com/Leaflet/Leaflet.markercluster)
 
This PR will let you directly publish updated versions of the library as they become available. All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as a maintainer.

I've already published the current version of the package on [Atmosphere](https://atmospherejs.com/prunecluster/prunecluster) (Meteor's package directory).  When you release new versions, you can publish them to Atmosphere with `grunt meteor`.

Thanks & best regards,
Pawel

### CODE REVIEW

**Comment by simison** [comment]
+1

**Comment by yellowiscool** [comment]
Hi,
I never used Meteor so I don't think I can maintain an integration but if I understand correctly Atmosphere is an alternative to Bower or NPM.

I created a Meteor account : ```sintef9012```

Also, thank you for the pull-request and the already published version.

**Comment by simison** [comment]
I can help testing Meteor integration every now and then and ping @mordka if something breaks.

**Comment by yellowiscool** [comment]
Great :-)

**Comment by mordka** [comment]
Awesome! :+1: 
@yellowiscool, I've added you to meteor organisation *prunecluster*. From now on, you can publish new versions to Metor's NPM - Atmosphere :)

@simison, Thanks for support, testing is crucial :) I'm already using the library, because I think it's better then the official one from Leaflet.

**Pull request merged**
